---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Installing pre dependencies of xorg-server
  include: pre_install.yaml

- name: Merge pre defined xorg packages and packages defined by user
  set_fact:
    xorg_packages: "{{ __xorg_packages|list }}"
  when: xorg_packages is not defined

- name: Set the default display manager xdm
  set_fact:
    xorg_display_manager_package: "{{ __xorg_display_manager_package }}"
  when: xorg_display_manager_package is not defined

- name: Set the default display manager service name
  set_fact:
    xorg_display_manager_service: "{{ __xorg_display_manager_service }}"
  when: xorg_display_manager_service is not defined

- name: Merge default fonts and user defined font
  set_fact:
    xorg_fonts: "{{ __xorg_fonts|list }}"
  when: xorg_fonts is not defined

- name: Installing xorg-server and sufficient packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ xorg_packages }}"

- name: Setting Keymap and Keyboard modell
  template:
    src: 00-keyboard.conf.j2
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Archlinux"

- name: Installing xorg-font and user chosen fonts
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ xorg_fonts }}"
  notify: Restart display manager

- name: Installing display manager package
  package:
    name: "{{ item }}"
  with_items: "{{ xorg_display_manager_package }}"
  notify: Restart display manager

- name: Enable "{{ xorg_display_manager_service }}"
  service:
    name: "{{ xorg_display_manager_service }}"
    enabled: True
    state: started

